# Generated by Django 4.0.6 on 2023-03-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='print_options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_name', models.CharField(max_length=200, verbose_name='printername')),
                ('doc_file', models.CharField(max_length=300, verbose_name='docfile')),
                ('copies', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='copies')),
                ('layout', models.CharField(max_length=300, verbose_name='layout')),
                ('colored', models.CharField(max_length=300, verbose_name='colored')),
                ('sizee', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='sizee')),
                ('pages', models.CharField(max_length=300, verbose_name='pages')),
            ],
        ),
    ]
